[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "daphne>=4.1.2",
    "django>=5.1.7",
    "fastapi>=0.115.12",
    "pydantic>=2.10.6",
    "sqlalchemy==2.0.36",
    "uvicorn>=0.34.0",
]
